version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped
    networks:
      - mongo-network

  #Mongo UI to test locally
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - mongo-network

  # Express.js
  backend:
    build: ./backend
    container_name: express_backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/freshdb?authSource=admin
    command: ["sh", "-c", "node seed.js && node server.js"]
    networks:
      - mongo-network

  # # Angular Frontend
  # frontend:
  #   build: ./frontend
  #   container_name: angular_frontend
  #   ports:
  #     - "4200:4200"
  #   depends_on:
  #     - backend

volumes:
  mongodb_data:

networks:
  mongo-network:
    driver: bridge